#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Applies configuration values to Azure App Configuration and Key Vault based on generated metadata.

.DESCRIPTION
    Reads the configuration-metadata.json file generated by the source generator and applies
    values from environment variables or parameter files to Azure App Configuration and Key Vault.

.PARAMETER MetadataFile
    Path to the configuration-metadata.json file generated by the source generator.

.PARAMETER AppConfigName
    Name of the Azure App Configuration store.

.PARAMETER KeyVaultName
    Name of the Azure Key Vault.

.PARAMETER ParameterFile
    Optional JSON file containing non-secret configuration values.
    Format: { "values": { "Key:Name": "value", ... } }

.PARAMETER ValidateOnly
    If specified, only validates that required values are present without applying them.

.PARAMETER FailOnMissing
    If specified, script will fail if any required values are missing. Default is true.

.EXAMPLE
    ./Apply-ConfigValues.ps1 `
        -MetadataFile "./configuration-metadata.json" `
        -AppConfigName "appconfig-myapp-dev" `
        -KeyVaultName "kv-myapp-dev" `
        -ParameterFile "./parameters.dev.json"

.EXAMPLE
    # Validation only
    ./Apply-ConfigValues.ps1 `
        -MetadataFile "./configuration-metadata.json" `
        -AppConfigName "appconfig-myapp-dev" `
        -KeyVaultName "kv-myapp-dev" `
        -ValidateOnly

.NOTES
    Secrets should be provided via environment variables, not in parameter files.
    Environment variable names should match the key with colons replaced by hyphens.
    Example: "Database:Password" -> Environment variable "Database-Password"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$MetadataFile,

    [Parameter(Mandatory = $true)]
    [string]$AppConfigName,

    [Parameter(Mandatory = $true)]
    [string]$KeyVaultName,

    [Parameter(Mandatory = $false)]
    [string]$ParameterFile,

    [Parameter(Mandatory = $false)]
    [switch]$ValidateOnly,

    [Parameter(Mandatory = $false)]
    [bool]$FailOnMissing = $true
)

$ErrorActionPreference = "Stop"

# Colors for output
$ColorSuccess = "Green"
$ColorWarning = "Yellow"
$ColorError = "Red"
$ColorInfo = "Cyan"

function Write-ColorOutput {
    param(
        [string]$Message,
        [string]$Color = "White"
    )
    Write-Host $Message -ForegroundColor $Color
}

# Validate metadata file exists
if (-not (Test-Path $MetadataFile)) {
    Write-ColorOutput "❌ Metadata file not found: $MetadataFile" $ColorError
    exit 1
}

Write-ColorOutput "📋 Reading configuration metadata from: $MetadataFile" $ColorInfo
$metadata = Get-Content $MetadataFile | ConvertFrom-Json

# Load parameter file if provided
$parameterValues = @{}
if ($ParameterFile -and (Test-Path $ParameterFile)) {
    Write-ColorOutput "📄 Loading parameter file: $ParameterFile" $ColorInfo
    $params = Get-Content $ParameterFile | ConvertFrom-Json
    if ($params.values) {
        $params.values.PSObject.Properties | ForEach-Object {
            $parameterValues[$_.Name] = $_.Value
        }
    }
}

# Track results
$appliedCount = 0
$skippedCount = 0
$errorCount = 0
$errors = @()

# Function to get value from environment or parameter file
function Get-ConfigValue {
    param(
        [string]$Key,
        [string]$DefaultValue,
        [bool]$IsSecret
    )

    $envVarName = $Key.Replace(':', '-')

    # Try environment variable first
    $value = [Environment]::GetEnvironmentVariable($envVarName)

    # If not in environment, try parameter file (only for non-secrets)
    if (-not $value -and -not $IsSecret) {
        $value = $parameterValues[$Key]
    }

    # Fall back to default value
    if (-not $value -and $DefaultValue) {
        $value = $DefaultValue
    }

    return $value
}

Write-ColorOutput "`n🔧 Processing Configuration Entries" $ColorInfo
Write-ColorOutput "====================================" $ColorInfo

# Process config entries (App Configuration)
foreach ($entry in $metadata.configEntries) {
    $key = $entry.key
    $required = $entry.required
    $defaultValue = $entry.defaultValue

    $value = Get-ConfigValue -Key $key -DefaultValue $defaultValue -IsSecret $false

    if ($value) {
        Write-ColorOutput "  ✓ $key" $ColorSuccess

        if (-not $ValidateOnly) {
            try {
                az appconfig kv set `
                    --name $AppConfigName `
                    --key $key `
                    --value $value `
                    --yes `
                    2>&1 | Out-Null

                $appliedCount++
            }
            catch {
                Write-ColorOutput "    ❌ Failed to set: $_" $ColorError
                $errors += "Failed to set config '$key': $_"
                $errorCount++
            }
        }
        else {
            $appliedCount++
        }
    }
    elseif ($required) {
        Write-ColorOutput "  ❌ $key (REQUIRED - MISSING)" $ColorError
        $errors += "Required configuration missing: $key"
        $errorCount++
    }
    else {
        Write-ColorOutput "  ⊘ $key (optional, not provided)" $ColorWarning
        $skippedCount++
    }
}

Write-ColorOutput "`n🔐 Processing Secret Entries" $ColorInfo
Write-ColorOutput "=============================" $ColorInfo

# Process secret entries (Key Vault)
foreach ($entry in $metadata.secretEntries) {
    $key = $entry.key
    $secretName = $key.Replace(':', '-')
    $required = $entry.required

    $value = Get-ConfigValue -Key $key -DefaultValue $null -IsSecret $true

    if ($value) {
        Write-ColorOutput "  ✓ $secretName" $ColorSuccess

        if (-not $ValidateOnly) {
            try {
                az keyvault secret set `
                    --vault-name $KeyVaultName `
                    --name $secretName `
                    --value $value `
                    2>&1 | Out-Null

                $appliedCount++
            }
            catch {
                Write-ColorOutput "    ❌ Failed to set: $_" $ColorError
                $errors += "Failed to set secret '$secretName': $_"
                $errorCount++
            }
        }
        else {
            $appliedCount++
        }
    }
    elseif ($required) {
        Write-ColorOutput "  ❌ $secretName (REQUIRED - MISSING)" $ColorError
        $errors += "Required secret missing: $key (set environment variable: $($key.Replace(':', '-')))"
        $errorCount++
    }
    else {
        Write-ColorOutput "  ⊘ $secretName (optional, not provided)" $ColorWarning
        $skippedCount++
    }
}

# Summary
Write-ColorOutput "`n📊 Summary" $ColorInfo
Write-ColorOutput "==========" $ColorInfo
Write-ColorOutput "  ✓ Applied/Valid: $appliedCount" $ColorSuccess
Write-ColorOutput "  ⊘ Skipped: $skippedCount" $ColorWarning
Write-ColorOutput "  ❌ Errors: $errorCount" $(if ($errorCount -gt 0) { $ColorError } else { $ColorSuccess })

if ($errors.Count -gt 0) {
    Write-ColorOutput "`n❌ Errors Encountered:" $ColorError
    $errors | ForEach-Object {
        Write-ColorOutput "  - $_" $ColorError
    }
}

# Exit with appropriate code
if ($errorCount -gt 0 -and $FailOnMissing) {
    Write-ColorOutput "`n❌ Configuration application failed" $ColorError
    exit 1
}
elseif ($errorCount -gt 0) {
    Write-ColorOutput "`n⚠️  Configuration applied with warnings" $ColorWarning
    exit 0
}
else {
    Write-ColorOutput "`n✅ Configuration application successful!" $ColorSuccess
    exit 0
}
